[References]

;NorDragonStatueBend02|NorDragonStatueBend02Snow
0x039E00~Skyrim.esm|0x801~Stretched Snow Begone BOS Update.esp
0x039E01~Skyrim.esm|0x801~Stretched Snow Begone BOS Update.esp

;NorDragonStatueBend01|NorDragonStatueBend01Snow
0x039DFD~Skyrim.esm|0x802~Stretched Snow Begone BOS Update.esp
0x039DFE~Skyrim.esm|0x802~Stretched Snow Begone BOS Update.esp
