# Fix loadorder.txt after task-0030: merge snapshot Lux ordering + enable Syn outputs.
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/Mo2ProfileGuardrails.ps1"

Assert-Mo2Closed

$repoRoot = Split-Path $PSScriptRoot -Parent
$snapDir = Join-Path $repoRoot 'modlist\exports\mlo2-pre-migration-2026-07-07'
$profileDir = Join-Path $script:AnvilRoot "profiles\$script:AnvilProfile"
$pluginsPath = Join-Path $profileDir 'plugins.txt'
$loadorderPath = Join-Path $profileDir 'loadorder.txt'

function Get-PluginBaseName {
    param([string]$Line)
    if ($Line -match '^\*?(.+\.(esp|esm|esl))$') { return $Matches[1] }
    return $null
}

$snapLoad = @(Get-Content (Join-Path $snapDir 'loadorder.txt') | Where-Object { $_ -notmatch '^#' -and $_.Trim() -ne '' })
$active = @{}
Get-Content -LiteralPath $pluginsPath |
    Where-Object { $_ -match '^\*' } |
    ForEach-Object {
        $n = Get-PluginBaseName $_
        if ($n) { $active[$n.ToLowerInvariant()] = $n }
    }

# Re-enable Syn frozen outputs if present on disk
$pluginLines = @(Get-Content -LiteralPath $pluginsPath)
foreach ($syn in @('ANV_SynWorldPatcher.esp', 'ANV_SynW4ENBPatcher.esp')) {
    $found = $false
    for ($i = 0; $i -lt $pluginLines.Count; $i++) {
        if ((Get-PluginBaseName $pluginLines[$i]) -eq $syn) {
            $pluginLines[$i] = "*$syn"
            $active[$syn.ToLowerInvariant()] = $syn
            $found = $true
            break
        }
    }
    if (-not $found) {
        $pluginLines += "*$syn"
        $active[$syn.ToLowerInvariant()] = $syn
    }
}
$pluginLines | Set-Content -LiteralPath $pluginsPath

$ordered = [System.Collections.Generic.List[string]]::new()
$seen = @{}
foreach ($p in $snapLoad) {
    if ($active.ContainsKey($p.ToLowerInvariant()) -and -not $seen.ContainsKey($p.ToLowerInvariant())) {
        [void]$ordered.Add($active[$p.ToLowerInvariant()])
        $seen[$p.ToLowerInvariant()] = $true
    }
}

# Append post-snapshot active plugins (Pandora/USMP ordering drift, etc.) preserving current relative order
$curLoad = @(Get-Content -LiteralPath $loadorderPath | Where-Object { $_ -notmatch '^#' -and $_.Trim() -ne '' })
foreach ($p in $curLoad) {
    if ($active.ContainsKey($p.ToLowerInvariant()) -and -not $seen.ContainsKey($p.ToLowerInvariant())) {
        [void]$ordered.Add($active[$p.ToLowerInvariant()])
        $seen[$p.ToLowerInvariant()] = $true
    }
}
foreach ($p in $active.Values) {
    if (-not $seen.ContainsKey($p.ToLowerInvariant())) {
        [void]$ordered.Add($p)
    }
}

@('# This file was automatically generated by Mod Organizer.') + $ordered | Set-Content -LiteralPath $loadorderPath
Write-Host "loadorder.txt rebuilt: $($ordered.Count) plugins (snapshot-first merge)."
