[Reference]
;ShipLongBoat01_Snow
0x09a38e~Skyrim.esm|0x800~Snowy Ships for Snowy Regions.esp
0x0d67ec~Skyrim.esm|0x800~Snowy Ships for Snowy Regions.esp
0x05164f~Skyrim.esm|0x800~Snowy Ships for Snowy Regions.esp
0x05164e~Skyrim.esm|0x800~Snowy Ships for Snowy Regions.esp
0x05227f~Skyrim.esm|0x800~Snowy Ships for Snowy Regions.esp
0x016fde~Dragonborn.esm|0x800~Snowy Ships for Snowy Regions.esp
0x01ae20~Dragonborn.esm|0x800~Snowy Ships for Snowy Regions.esp

;ShipLongBoatWrecks_Snow
0x074ff2~Skyrim.esm|0xd7a~Snowy Ships for Snowy Regions.esp
0x074ff0~Skyrim.esm|0xd79~Snowy Ships for Snowy Regions.esp
0x074ff1~Skyrim.esm|0xd78~Snowy Ships for Snowy Regions.esp

;ShipStairs01_Snow
0x0e9638~Skyrim.esm|0x801~Snowy Ships for Snowy Regions.esp
0x099ae9~Skyrim.esm|0x801~Snowy Ships for Snowy Regions.esp
0x10f861~Skyrim.esm|0x801~Snowy Ships for Snowy Regions.esp
0x0e9635~Skyrim.esm|0x801~Snowy Ships for Snowy Regions.esp
0x016fdf~Dragonborn.esm|0x801~Snowy Ships for Snowy Regions.esp
0x01ae29~Dragonborn.esm|0x801~Snowy Ships for Snowy Regions.esp
0x03abd1~Dragonborn.esm|0x801~Snowy Ships for Snowy Regions.esp

;ShipLarge01_Snow
0x02498e~Skyrim.esm|0x802~Snowy Ships for Snowy Regions.esp
0x074452~Skyrim.esm|0x802~Snowy Ships for Snowy Regions.esp

;ShipAnchorWheel01_Snow
0x094b70~Skyrim.esm|0x803~Snowy Ships for Snowy Regions.esp

;ShipWoodBeamStraight01_Snow
0x094b91~Skyrim.esm|0x804~Snowy Ships for Snowy Regions.esp

;ShipWoodBeamStraight02_Snow
0x094b92~Skyrim.esm|0x805~Snowy Ships for Snowy Regions.esp

;ShipWoodBeamStraight03_Snow
0x094b93~Skyrim.esm|0x806~Snowy Ships for Snowy Regions.esp
0x074fc0~Skyrim.esm|0x806~Snowy Ships for Snowy Regions.esp

;ShipWoodplanks04_Snow
0x0e6d7b~Skyrim.esm|0x807~Snowy Ships for Snowy Regions.esp
0x0e6d7c~Skyrim.esm|0x807~Snowy Ships for Snowy Regions.esp

;FarmTable01_Snow
0x074fac~Skyrim.esm|0x808~Snowy Ships for Snowy Regions.esp

;ShipWoodplanks02_Snow
0x074fc3~Skyrim.esm|0x809~Snowy Ships for Snowy Regions.esp
0x094b9f~Skyrim.esm|0x809~Snowy Ships for Snowy Regions.esp

;CrateSmall03_Snow
0x0a3647~Skyrim.esm|0x80b~Snowy Ships for Snowy Regions.esp
0x0a3644~Skyrim.esm|0x80b~Snowy Ships for Snowy Regions.esp
0x0a3625~Skyrim.esm|0x80b~Snowy Ships for Snowy Regions.esp
0x0a38f2~Skyrim.esm|0x80b~Snowy Ships for Snowy Regions.esp
0x0a38f9~Skyrim.esm|0x80b~Snowy Ships for Snowy Regions.esp
0x0a38f8~Skyrim.esm|0x80b~Snowy Ships for Snowy Regions.esp

;CrateSmall02_Snow
0x0a36a4~Skyrim.esm|0x80c~Snowy Ships for Snowy Regions.esp
0x0a361b~Skyrim.esm|0x80c~Snowy Ships for Snowy Regions.esp
0x0a38fb~Skyrim.esm|0x80c~Snowy Ships for Snowy Regions.esp
0x0a38f1~Skyrim.esm|0x80c~Snowy Ships for Snowy Regions.esp
0x01d79c~Dragonborn.esm|0x80c~Snowy Ships for Snowy Regions.esp

;CrateSmall01_Snow
0x0a3614~Skyrim.esm|0x80d~Snowy Ships for Snowy Regions.esp
0x0a36a3~Skyrim.esm|0x80d~Snowy Ships for Snowy Regions.esp
0x0a38f0~Skyrim.esm|0x80d~Snowy Ships for Snowy Regions.esp

;CrateSmall04_Snow
0x01d79e~Dragonborn.esm|0x80f~Snowy Ships for Snowy Regions.esp

;CrateSmallLong01_Snow_Snow
0x01d799~Dragonborn.esm|0x810~Snowy Ships for Snowy Regions.esp

;Barrel02Static_Snow
0x0a3636~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x0a362e~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x0a3635~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x0a362d~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x0a3637~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x0a38f7~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x0a38f3~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x0a38f4~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x0a38f5~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x0a38f6~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b86~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b84~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b82~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b81~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b83~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b85~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b6e~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b76~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b7e~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b7d~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b67~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b6f~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b77~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b79~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b68~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b94~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b69~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b7a~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b6b~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b6a~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b78~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b6d~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b7f~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b7b~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b7c~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094b6c~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094ba2~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094ba4~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094ba3~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094ba1~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x094ba0~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x074fc8~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x074fc9~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x074fcf~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x074fc4~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x074fc5~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x074fbf~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x074fc1~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x074fc2~Skyrim.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x01d79a~Dragonborn.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x01d79d~Dragonborn.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x037709~Dragonborn.esm|0x80e~Snowy Ships for Snowy Regions.esp
0x037707~Dragonborn.esm|0x80e~Snowy Ships for Snowy Regions.esp

;ShipRowBoat01_Snow
0x0bb3d0~Skyrim.esm|0x811~Snowy Ships for Snowy Regions.esp
0x077e8a~Skyrim.esm|0x811~Snowy Ships for Snowy Regions.esp
0x077e85~Skyrim.esm|0x811~Snowy Ships for Snowy Regions.esp
0x0debab~Skyrim.esm|0x811~Snowy Ships for Snowy Regions.esp

;ShipRowBoatAnim01_Snow
0x09a389~Skyrim.esm|0xd74~Snowy Ships for Snowy Regions.esp
0x09a38a~Skyrim.esm|0xd74~Snowy Ships for Snowy Regions.esp
0x09a38d~Skyrim.esm|0xd74~Snowy Ships for Snowy Regions.esp
0x0c5326~Skyrim.esm|0xd74~Snowy Ships for Snowy Regions.esp
;0x077e88~Skyrim.esm|0xd74~Snowy Ships for Snowy Regions.esp
;0x077e87~Skyrim.esm|0xd74~Snowy Ships for Snowy Regions.esp
;0x077e89~Skyrim.esm|0xd74~Snowy Ships for Snowy Regions.esp
;0x077e86~Skyrim.esm|0xd74~Snowy Ships for Snowy Regions.esp
0x07f8a2~Skyrim.esm|0xd74~Snowy Ships for Snowy Regions.esp
0x07501c~Skyrim.esm|0xd74~Snowy Ships for Snowy Regions.esp
0x074fed~Skyrim.esm|0xd74~Snowy Ships for Snowy Regions.esp
0x0961ea~Skyrim.esm|0xd74~Snowy Ships for Snowy Regions.esp
0x016852~Dawnguard.esm|0xd74~Snowy Ships for Snowy Regions.esp